FROM docker:stable

LABEL "name"="Echo Action"
LABEL "maintainer"="Stephen Coakley <me@stephencoakley.com>"

LABEL "com.github.actions.name"="Echo"
LABEL "com.github.actions.description"="Run an echo command."
LABEL "com.github.actions.icon"="terminal"
LABEL "com.github.actions.color"="white"

ENTRYPOINT ["/bin/echo"]
